<?php

return [
    'USA' => [
        'steps' => [
            [
                'id' => 'dashboard',
                'label' => 'Dashboard',
                'icon' => 'chart-bar',
                'path' => '/dashboard',
                'order' => 1,
                'is_active' => true,
            ],
            [
                'id' => 'employees',
                'label' => 'Employees',
                'icon' => 'users',
                'path' => '/employees',
                'order' => 2,
                'is_active' => true,
            ],
        ],
        'columns' => [
            ['key' => 'name', 'label' => 'Name', 'type' => 'text', 'sortable' => true],
            ['key' => 'last_name', 'label' => 'Last Name', 'type' => 'text', 'sortable' => true],
            ['key' => 'salary', 'label' => 'Salary', 'type' => 'currency', 'sortable' => true],
            ['key' => 'ssn', 'label' => 'SSN', 'type' => 'masked', 'sortable' => false],
        ],
        'dashboard_widgets' => [
            [
                'id' => 'employee_count',
                'type' => 'stat_card',
                'title' => 'Total Employees',
                'data_source' => '/api/checklists?country=USA',
                'data_key' => 'total_employees',
                'refresh_channel' => 'country.USA',
                'refresh_event' => 'employee.list.updated',
                'size' => 'small',
                'position' => ['row' => 1, 'col' => 1],
            ],
            [
                'id' => 'average_salary',
                'type' => 'stat_card',
                'title' => 'Average Salary',
                'data_source' => '/api/employees?country=USA',
                'data_key' => 'average_salary',
                'refresh_channel' => 'country.USA',
                'refresh_event' => 'employee.list.updated',
                'size' => 'small',
                'position' => ['row' => 1, 'col' => 2],
            ],
            [
                'id' => 'completion_rate',
                'type' => 'progress_card',
                'title' => 'Checklist Completion Rate',
                'data_source' => '/api/checklists?country=USA',
                'data_key' => 'overall_completion',
                'refresh_channel' => 'checklist.USA',
                'refresh_event' => 'checklist.updated',
                'size' => 'small',
                'position' => ['row' => 1, 'col' => 3],
            ],
        ],
    ],

    'Germany' => [
        'steps' => [
            [
                'id' => 'dashboard',
                'label' => 'Dashboard',
                'icon' => 'chart-bar',
                'path' => '/dashboard',
                'order' => 1,
                'is_active' => true,
            ],
            [
                'id' => 'employees',
                'label' => 'Employees',
                'icon' => 'users',
                'path' => '/employees',
                'order' => 2,
                'is_active' => true,
            ],
            [
                'id' => 'documentation',
                'label' => 'Documentation',
                'icon' => 'document-text',
                'path' => '/documentation',
                'order' => 3,
                'is_active' => true,
            ],
        ],
        'columns' => [
            ['key' => 'name', 'label' => 'Name', 'type' => 'text', 'sortable' => true],
            ['key' => 'last_name', 'label' => 'Last Name', 'type' => 'text', 'sortable' => true],
            ['key' => 'salary', 'label' => 'Salary', 'type' => 'currency', 'sortable' => true],
            ['key' => 'goal', 'label' => 'Goal', 'type' => 'text', 'sortable' => false],
        ],
        'dashboard_widgets' => [
            [
                'id' => 'employee_count',
                'type' => 'stat_card',
                'title' => 'Total Employees',
                'data_source' => '/api/checklists?country=Germany',
                'data_key' => 'total_employees',
                'refresh_channel' => 'country.Germany',
                'refresh_event' => 'employee.list.updated',
                'size' => 'small',
                'position' => ['row' => 1, 'col' => 1],
            ],
            [
                'id' => 'goal_tracking',
                'type' => 'list_card',
                'title' => 'Goal Tracking',
                'data_source' => '/api/checklists?country=Germany',
                'data_key' => 'employees',
                'refresh_channel' => 'checklist.Germany',
                'refresh_event' => 'checklist.updated',
                'size' => 'large',
                'position' => ['row' => 1, 'col' => 2],
            ],
        ],
    ],
];
